name: Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    defaults:
      run:
        working-directory: ./back-end-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Manage NPM Dependencies
        uses: ./.github/actions/cache-node-dependencies
        with:
          app-name: "nest-app"
          working-directory: "./back-end-app"

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: back-end-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
